// AUTH
export const AUTH = 'AUTH';
export const GOOGLEAUTH = 'GOOGLEAUTH';
export const LOGOUT = 'LOGOUT';

export const CREATE_PROFILE = 'CREATE_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const DELETE_PROFILE = 'DELETE_PROFILE';
export const FETCH_PROFILES = 'FETCH_PROFILES';
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_PROFILE_BY_USER = 'FETCH_PROFILE_USER';
export const FETCH_PROFILES_BY_USER = 'FETCH_PROFILES_BY_USER';

export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const CATEGORY_FETCH_FAILURE = 'CATEGORY_FETCH_FAILURE';
export const SUBCATEGORY_FETCH_SUCCESS = 'SUBCATEGORY_FETCH_SUCCESS';
export const SUBCATEGORY_FETCH_FAILURE = 'SUBCATEGORY_FETCH_FAILURE';
